language: d
os:
  - linux
  - osx
env:
  - secure: "NV1Ow4YXogPx/kevm0kGesSoblvgv+9z3uhzrWhDDSfTlib845b+dLJyjLY/SRfUaJ0Mew6kOnqLoyISmpe0E3KkbMDh/t+jU1ueqR/FWLsdBRcUMfkC3amJ8GS0zRnbREaAG37p6YShScCjazrf0w9opM0hzHqkXLj2kev68lk="
install:
  - echo $TRAVIS_OS_NAME $TRAVIS_JOB_ID
  - bash .travis/setup_linux.sh
  - bash .travis/setup_osx.sh
  - sudo dub fetch x11
  - sudo dub fetch doveralls
  # Install new dub
  - git clone https://github.com/ColdenCullen/dub
  - cd dub && dub build
  - cd ..
script: sudo ./dub/bin/dub test-cov
after_success: sudo dub run doveralls -- -p `pwd` -j $TRAVIS_JOB_ID
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/89d5205a2483bcd72a32
    on_success: change
    on_failure: always
    on_start: never
