sudo: false
language: d
d:
  - dmd
  - ldc
os:
  - linux
  - osx

script: 
  - dub test --compiler=${DC} --coverage

after_success:
  - dub fetch doveralls
  - dub run doveralls -- -p `pwd` -j $TRAVIS_JOB_ID

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/89d5205a2483bcd72a32
    on_success: change
    on_failure: always
    on_start: never
