language: d
os:
  - linux
  - osx
install:
  - echo $TRAVIS_OS_NAME $TRAVIS_JOB_ID
  - bash .travis/setup_linux.sh
  - bash .travis/setup_osx.sh
  - sudo dub fetch x11
  - sudo dub fetch doveralls
  # Install new dub
  - git clone https://github.com/D-Programming-Language/dub
  - cd dub && dub build
  - cd ..
script: sudo ./dub/bin/dub test --coverage
after_success: sudo dub run doveralls -- -p `pwd` -j $TRAVIS_JOB_ID
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/89d5205a2483bcd72a32
    on_success: change
    on_failure: always
    on_start: never
